ServerName localhost

LoadModule rewrite_module modules/mod_rewrite.so

<Directory "/usr/local/apache2/htdocs">
    Options FollowSymLinks
    AllowOverride None
    Require all granted

    RewriteEngine On
    # ファイルやディレクトリが存在しない場合は index.html を返す
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
</Directory>
